apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: tailscale-k0s
spec:
  hosts:
  - hostname: control-plane-01
    privateAddress: 100.73.177.12
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.73.177.12
      user: root
      port: 22
  - hostname: control-plane-02
    privateAddress: 100.65.64.14
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.65.64.14
      user: root
      port: 22
  - hostname: control-plane-03
    privateAddress: 100.125.156.96
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.125.156.96
      user: root
      port: 22
  - hostname: node-01
    privateAddress: 100.84.67.79
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.84.67.79
      user: root
      port: 22
  - hostname: node-02
    privateAddress: 100.98.33.7
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.98.33.7
      user: root
      port: 22
  - hostname: node-03
    privateAddress: 100.118.229.98
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.118.229.98
      user: root
      port: 22
  - hostname: node-04
    privateAddress: 100.106.131.26
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.106.131.26
      user: root
      port: 22
  - hostname: node-05
    privateAddress: 100.114.245.5
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.114.245.5
      user: root
      port: 22
  k0s:
    version: v1.36.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: tailscale-k0s
      spec:
        api:
          onlyBindToAddress: true
          sans:
          - control-plane-01
          - control-plane-02
          - control-plane-03
          - 100.73.177.12
          - 100.65.64.14
          - 100.125.156.96
        network:
          provider: custom
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          kubeProxy:
            disabled: true
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
  options:
    wait:
      enabled: false
