apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: tailscale-k0s
spec:
  hosts:
  - hostname: control-plane-01
    privateAddress: 100.86.220.5
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.86.220.5
      user: root
      port: 22
  - hostname: control-plane-02
    privateAddress: 100.71.238.104
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.71.238.104
      user: root
      port: 22
  - hostname: control-plane-03
    privateAddress: 100.112.245.5
    privateInterface: tailscale0
    role: controller
    ssh:
      address: 100.112.245.5
      user: root
      port: 22
  - hostname: node-01
    privateAddress: 100.116.95.79
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.116.95.79
      user: root
      port: 22
  - hostname: node-02
    privateAddress: 100.127.198.66
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.127.198.66
      user: root
      port: 22
  - hostname: node-03
    privateAddress: 100.94.184.38
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.94.184.38
      user: root
      port: 22
  - hostname: node-04
    privateAddress: 100.66.160.66
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.66.160.66
      user: root
      port: 22
  - hostname: node-05
    privateAddress: 100.120.47.6
    privateInterface: tailscale0
    role: worker
    ssh:
      address: 100.120.47.6
      user: root
      port: 22
  k0s:
    version: v1.36.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: tailscale-k0s
      spec:
        api:
          onlyBindToAddress: true
          sans:
          - control-plane-01
          - control-plane-02
          - control-plane-03
          - 100.86.220.5
          - 100.71.238.104
          - 100.112.245.5
        network:
          provider: custom
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          kubeProxy:
            disabled: true
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
  options:
    wait:
      enabled: false
