[settings]
pipx.uvx = true
lockfile = true
disable_backends = ["asdf", "vfox"]

[tools]
python = "3.14.7"
uv = { version = "0.12.4", depends = ["python"] }
"pipx:ansible" = { version = "14.3.0", uvx_args = "--with-executables-from ansible-core,ansible-lint", depends = ["uv"] }
kubectl = "1.36.3"
cilium-cli = "0.19.7"
gh = "2.97.0"
k0sctl = "0.32.2"
helm = "4.2.4"
sops = "3.13.3"
age = "1.3.1"
"aqua:cilium/hubble" = "1.19.4"

[tasks."docker:build:trixie-base"]
description = "Build the base image for trixie"
dir = "base"
run = "docker build -t ghcr.io/vancanhuit/debian-rootfs:trixie-base ."

[tasks."docker:build:trixie-dev"]
description = "Build the development image for trixie"
env = { GITHUB_TOKEN = "{{ exec(command='gh auth token') }}" }
dir = "dev"
run = '''
docker build \
    --secret id=github_token,env=GITHUB_TOKEN \
    -t ghcr.io/vancanhuit/debian-rootfs:trixie-dev .
'''
