[incus]
incus-01
incus-02
incus-03

[incus:vars]
ansible_user=root
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3.13
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o ProxyCommand="tailscale nc %h %p"
