all:
  vars:
    tailscale_domain: tailaa4bf1.ts.net

k8s:
  children:
    k8s_control_plane:
      hosts:
        control-plane-01:
        control-plane-02:
        control-plane-03:
    k8s_node:
      hosts:
        node-01:
        node-02:
        node-03:
        node-04:
        node-05:
